name: 状态校准
on:
  schedule:
    - cron: '30 0 * * 1'
  workflow_dispatch:
jobs:
  cal:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
      - run: pip install requests
      - run: ls -la
      - env:
          TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          PUSHPLUS_TOPIC: ${{ secrets.PUSHPLUS_TOPIC }}
        run: python -u calibration.py
