name: Tushare连通测试
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v5
      - run: pip install requests
      - name: 测试Tushare
        env:
          TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
        run: python tushare_test.py
